site_name: EntropyLab

site_url: https://www.entropy-lab.io
site_author: EntropyLab contributors
site_description: >-
  Lab control and management for modular and scallable creation of quantum 
  workflows. Open-source enterprise-ready solution.

# Repository
repo_name: entropy-lab/entropylab-docs
repo_url: https://github.com/entropy-lab/entropylab-docs

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  palette:
    - scheme: entropy-bright
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: entropy-dark 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - minify_html: true
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - stylesheets/extra.css
extra:
  generator: false

nav:
  - Home: index.md
#  - "EntropyHub & Flame":
#    - "Overview": "entropyhub_flame/index.md"
#    - "Getting started": "entropyhub_flame/getting_started.md"
#    - NodeIO: "entropyhub_flame/nodeio/overview.md"
#    - Workflow: "entropyhub_flame/workflow/overview.md"
#    - Observability: "entropyhub_flame/observability/overview.md"
#    - Management of records: "entropyhub_flame/management_record/overview.md"
#    - Guide for contributors: "entropyhub_flame/contribute/overview.md"
  - Entropy CLI:
      - Getting started: "entropy-cli/getting_started.md"
      - An entropy project: "entropy-cli/project.md"
      - The dashboard: "entropy-cli/gui.md"
  - Pipeline:
    - The experiment graph: "pipeline/getting_started.md"
    - The context: "pipeline/entropy_context.md"
    - Entropy & QUA: "pipeline/entropy_qua.md"
    - Plotting: "pipeline/plotting.md"
#    - API: "pipeline/API.md"
#  - QuAM:
#    - Overview: "quam/overview.md"
  - ParameterStore: "paramstore/overview.md"
#  - Guide for contributors: "contribute/overview.md"

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - abbr
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings