site_name: Entropylab Documentation

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: entropy
  features:
    - search
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
repo_url: https://github.com/entropy-lab/entropylab/
repo_name: entropy-lab/entropylab
extra_css:
  - stylesheets/extra.css
extra:
  generator: false

nav:
  - Getting started: "getting_started.md"
  - QuAM: "quam/overview.md"
  - ParameterStore: "paramstore/overview.md"
#  - Guide for contributors: "contribute/overview.md"

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js